apiVersion: apps/v1
kind: Deployment
metadata:
  name: th3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: th3
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: th3
    spec:
      containers:
      - image: craigmdupree/th3:0.0.1
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /version
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        name: th3
        ports:
        - containerPort: 8000
